---
- name: Upgrade pip
  shell: "pip3 install --upgrade pip"
  when: python_pip_upgrade
  tags: [bigchaindb-driver]

- name: Upgrade setuptools
  shell: "pip3 install --upgrade setuptools"
  when: python_setuptools_upgrade
  tags: [bigchaindb-driver]

- name: Install BigchainDB Driver
  shell: "pip3 install bigchaindb-driver"
  tags: [bigchaindb-driver]

- name: Install Cryptoconditions
  shell: "pip3 install cryptoconditions"
  tags: [bigchaindb-driver]

- name: Install base58
  shell: "pip3 install base58"
  tags: [bigchaindb-driver]

- name: Install json
  shell: "pip3 install json"
  tags: [bigchaindb-driver]

- name: Install sha3
  shell: "pip3 install sha3"
  tags: [bigchaindb-driver]
