---
dependencies_deb:
  - libffi-dev
  - libssl-dev

dependencies_yum:
  - gcc-c++
  - "@Development Tools"
  - libffi-devel
  - openssl-devel

dependencies_dnf:
  - gcc-c++
  - redhat-rpm-config
  - "@Development Tools"
  - libffi-devel
  - openssl-devel

python_pip_upgrade: true
python_setuptools_upgrade: true

# Host configuration
distribution_name: "{{ ansible_distribution|lower }}"
distribution_codename: "{{ ansible_distribution_release|lower }}"
distribution_major: "{{ ansible_distribution_major_version }}"
